export const GENRES = [
	'',
	'A Cappella',
	'Abstract',
	'Acid',
	'Acid Jazz',
	'Acid Punk',
	'Acoustic',
	'Alternative',
	'Alternative Rock',
	'Ambient',
	'Anime',
	'Art Rock',
	'Audio Theatre',
	'Audiobook',
	'Avant-Garde',
	'Ballad',
	'Baroque',
	'Bass',
	'Beat Music',
	'Bebop',
	'Bhangra',
	'Big Band',
	'Big Beat',
	'Black Metal',
	'Bluegrass',
	'Blues',
	'Booty Bass',
	'Breakbeat',
	'Britpop',
	'Cabaret',
	'Celtic',
	'Chamber Music',
	'Chanson',
	'Chillout',
	'Chorus',
	'Christian Gangsta Rap',
	'Christian Rap',
	'Christian Rock',
	'Classic Rock',
	'Classical',
	'Club',
	'Club-House',
	'Comedy',
	'Contemporary Christian',
	'Country',
	'Crossover',
	'Cult',
	'Dance',
	'Dancehall',
	'Dark Wave',
	'Death Metal',
	'Disco',
	'Downtempo',
	'Dream',
	'Drum & Bass',
	'Drum Solo',
	'Dub',
	'Dubstep',
	'Duet',
	'EBM',
	'Easy Listening',
	'Eclectic',
	'Electro',
	'Electroclash',
	'Electronic',
	'Emo',
	'Ethnic',
	'Euro House',
	'Eurodance',
	'Eurotechno',
	'Experimental',
	'Fast Fusion',
	'Folk',
	'Folk Rock',
	'Folklore',
	'Freestyle',
	'Funk',
	'Fusion',
	'G-Funk',
	'Game',
	'Gangsta',
	'Garage',
	'Garage Rock',
	'Global',
	'Goa',
	'Gospel',
	'Gothic',
	'Gothic Rock',
	'Grunge',
	'Hard Rock',
	'Hardcore',
	'Heavy Metal',
	'Hip Hop',
	'House',
	'Humour',
	'IDM',
	'Illbient',
	'Indie',
	'Indie Rock',
	'Industrial',
	'Industro-Goth',
	'Instrumental',
	'Instrumental Pop',
	'Instrumental Rock',
	'Jam Band',
	'Jazz',
	'Jazz-Funk',
	'Jpop',
	'Jungle',
	'Krautrock',
	'Latin',
	'Leftfield',
	'Lo-Fi',
	'Lounge',
	'Math Rock',
	'Meditative',
	'Merengue',
	'Metal',
	'Musical',
	'National Folk',
	'Native American',
	'Neoclassical',
	'Neue Deutsche Welle',
	'New Age',
	'New Romantic',
	'New Wave',
	'Noise',
	'Nu-Breakz',
	'Oldies',
	'Opera',
	'Other',
	'Podcast',
	'Polka',
	'Polsk Punk',
	'Pop',
	'Pop-Folk',
	'Pop-Funk',
	'Porn Groove',
	'Post-Punk',
	'Post-Rock',
	'Power Ballad',
	'Pranks',
	'Primus',
	'Progressive Rock',
	'Psybient',
	'Psychedelic',
	'Psychedelic Rock',
	'Psytrance',
	'Punk',
	'Punk Rock',
	'R&B',
	'Rap',
	'Rave',
	'Reggae',
	'Retro',
	'Revival',
	'Rhythmic Soul',
	'Rock',
	'Rock & Roll',
	'Salsa',
	'Samba',
	'Satire',
	'Shoegaze',
	'Showtunes',
	'Ska',
	'Slow Jam',
	'Slow Rock',
	'Sonata',
	'Soul',
	'Sound Clip',
	'Soundtrack',
	'Southern Rock',
	'Space',
	'Space Rock',
	'Speech',
	'Swing',
	'Symphonic Rock',
	'Symphony',
	'Synth-Pop',
	'Tango',
	'Techno',
	'Techno-Industrial',
	'Terror',
	'Thrash Metal',
	'Top 40',
	'Trailer',
	'Trance',
	'Tribal',
	'Trip-Hop',
	'Trop Rock',
	'Vocal',
	'World Music',
	'Worldbeat',
]

const GENRE_MAP: Record<string, string> = {
	'60s': 'Oldies',
	'70s': 'Oldies',
	'80s': 'Oldies',
	'90s': 'Oldies',
	'acidjazz': 'Acid Jazz',
	'alternative': 'Alternative',
	'alternativerock': 'Alternative Rock',
	'ambient': 'Ambient',
	'atmospheric': 'Ambient',
	'blues': 'Blues',
	'bluesrock': 'Blues',
	'bossanova': 'Latin',
	'breakbeat': 'Breakbeat',
	'celtic': 'Celtic',
	'chanson': 'Chanson',
	'chillout': 'Chillout',
	'choir': 'Chorus',
	'classical': 'Classical',
	'classicrock': 'Classic Rock',
	'club': 'Club',
	'contemporary': 'Country',
	'country': 'Country',
	'dance': 'Dance',
	'darkambient': 'Ambient',
	'darkwave': 'Dark Wave',
	'deephouse': 'House',
	'disco': 'Disco',
	'downtempo': 'Downtempo',
	'drumnbass': 'Drum & Bass',
	'dub': 'Dub',
	'dubstep': 'Dubstep',
	'easylistening': 'Easy Listening',
	'edm': 'Dance',
	'electronic': 'Electronic',
	'electronica': 'Electronic',
	'electropop': 'Synth-Pop',
	'ethno': 'World Music',
	'eurodance': 'Eurodance',
	'experimental': 'Experimental',
	'folk': 'Folk',
	'funk': 'Funk',
	'fusion': 'Fusion',
	'groove': 'Funk',
	'grunge': 'Grunge',
	'hard': 'Hard Rock',
	'hardrock': 'Hard Rock',
	'hiphop': 'Hip Hop',
	'house': 'House',
	'idm': 'IDM',
	'improvisation': 'Jazz',
	'indie': 'Indie',
	'industrial': 'Industrial',
	'instrumentalpop': 'Instrumental Pop',
	'instrumentalrock': 'Instrumental Rock',
	'jazz': 'Jazz',
	'jazzfusion': 'Fusion',
	'latin': 'Latin',
	'lounge': 'Lounge',
	'medieval': 'Classical',
	'metal': 'Metal',
	'minimal': 'Ambient',
	'newage': 'New Age',
	'newwave': 'New Wave',
	'orchestral': 'Classical',
	'pop': 'Pop',
	'popfolk': 'Pop-Folk',
	'poprock': 'Pop',
	'postrock': 'Post-Rock',
	'progressive': 'Progressive Rock',
	'psychedelic': 'Psychedelic',
	'punkrock': 'Punk Rock',
	'rap': 'Rap',
	'reggae': 'Reggae',
	'rnb': 'R&B',
	'rock': 'Rock',
	'rocknroll': 'Rock & Roll',
	'singersongwriter': 'Folk',
	'soul': 'Soul',
	'soundtrack': 'Soundtrack',
	'swing': 'Swing',
	'symphonic': 'Symphonic Rock',
	'synthpop': 'Synth-Pop',
	'techno': 'Techno',
	'trance': 'Trance',
	'triphop': 'Trip-Hop',
	'world': 'World Music',
	'worldfusion': 'Fusion',
}

const KNOWN_GENRES_SET = new Set(GENRES.map((g) => g.toLowerCase()))

export function consolidateGenre(
	originalGenre: string,
	detectedGenre: string,
	ignoreOldGenres: Set<string> = new Set(),
): string {
	if (
		originalGenre &&
		KNOWN_GENRES_SET.has(originalGenre.toLowerCase()) &&
		!ignoreOldGenres.has(originalGenre.toLowerCase())
	) return originalGenre
	const key = detectedGenre.toLowerCase().replace(/[^a-z]/g, '')
	return GENRE_MAP[key] ?? detectedGenre
}
